### PR TITLE
Fix ac3 audio codec and add other missing audio codecs

### PR DESCRIPTION
**Pull request by Dinolek**

### CODE REVIEW

**Comment by Moyster** [comment]
Nice, thanks, I remember ffmpeg was taking over mtk omx for mp3 and maybe a few others, so I only added back flac on request and never tried to add more ffmpeg supported codecs :)

**Comment by Dinolek** [comment]
Btw, why you didn't switch to los-14.1-vendor. Are there any problems with it?

**Comment by Moyster** [comment]
Yeah, moving most of the blobs is fine but for some reasons mtk's decoders stopped working properly.  
Moving to /vendor needs some hexedit (some blobs have hardcoded /system/lib/ path, system<->vendor is 5 letters, so that's no big deal, but maybe I forgot to edit one. Recording a video works (can be read on PC) but playing/decoding any videos on the phone makes wierd grey bars (audio works iirc) also, I've sent you a mail on your commit adress, or you can add me on hgouts, as you were asking how to contact me.

cheers

**Comment by tribual** [comment]
Hi Moyster!

Wrote you on Hangouts, but you not answered till now. I think we maybe have the same problem on Elephone P9000. Would be nice to talk to you on hangouts...

THX

**Pull request merged**
